### ISSUE TITLE
Issues with mobile browsers

### ISSUE THREAD

**Issue by lijoev** [markashleybell/mab.jquery.taginput#16]
Since mobile has no enter key tags cant be added. I tried adding some other keycodes but of no use. Please help me.

**Comment by markashleybell** [comment]
Hi, I'm closing this because there is already an issue for it (#4). This library is quite old now and wasn't originally built with mobiles in mind, but unfortunately I just don't have time to do anything about it at the moment.

If you just Google 'jquery tag input', there are tons of better/more modern alternatives which may suit your needs; I'm afraid all I can suggest is trying one of them out.
